language: node_js
node_js: 
  - "stable"

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test-only

after_success:
  - npm run typedoc
  - npm pack

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "{YOURLIB}-*.tgz"
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    skip_cleanup: true
    email: "lorenzojlamas@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true

addons:
  sonarcloud:
    organization: "lorenzojlamas"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner